# Generated by Django 4.2.6 on 2025-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
