# Generated by Django 4.2.6 on 2025-05-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket_productbasket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbasket',
            old_name='basketid',
            new_name='basketId',
        ),
    ]
