# Generated by Django 4.2.6 on 2025-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_basketid_productbasket_basketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='produtCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
