# Generated by Django 4.2.6 on 2025-06-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productbasket_produtcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbasket',
            old_name='produtCount',
            new_name='productCount',
        ),
    ]
